### ISSUE TITLE
[css-values] Are the codepoints in an indentifier stored in escaped form or not?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#12982]
Imagine `a\ b` is parsed as an `<ident>`. What are the code points of the produced ident?

- Option 1: the indentifier is stored in escaped form
  1. `a`
  2. `\`
  3. ` `
  4. `b` 
- Option 2: the indentifier is stored raw
  1. `a`
  2. ` `
  3. `b` 

https://drafts.csswg.org/css-values/#css-css-identifier seems to assume option 1:

> CSS identifiers, generically denoted by `<ident>`, consist of a sequence of characters conforming to the [`<ident-token>`](https://drafts.csswg.org/css-syntax-3/#typedef-ident-token) grammar.

https://drafts.csswg.org/cssom/#serialize-an-identifier seems to assume option 2, since it escapes manually.

**Comment by tabatkins** [comment]
The Values text is not meant to imply anything about how things are stored. Syntax determines what the ident token is, and it records only the "raw" form.

**Comment by Loirooriol** [comment]
> CSS identifiers, generically denoted by `<ident>`, consist of a sequence of characters conforming to the [`<ident-token>`](https://drafts.csswg.org/css-syntax-3/#typedef-ident-token) grammar.

The character sequence `a`, ` `, `b` doesn't conform to the `<ident-token>` grammar:

<img width="865" height="161" src="https://github.com/user-attachments/assets/ab5539ee-43df-4e61-ad9e-abaf2df816c5" />

So CSS Values should instead say that the characters are the value of an `<ident-token>`.

**Comment by fantasai** [comment]
@Loirooriol Fixed in https://github.com/w3c/csswg-drafts/commit/d9675fd208d3a2e6c110a43946d5ac3c6748da0b ; please close out if this looks good!

**Comment by Loirooriol** [comment]
> and are written as an unquoted sequence of (potentially escaped) characters

It's still not much clear whether the sequence is before escaping, or after escaping.

I think adding an example would be useful.
