### ISSUE TITLE
Add [Exposed] to all interfaces

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#1818]
Needed for https://github.com/heycam/webidl/issues/365.

>  CSS Pseudo-Elements Module Level 4: CSSPseudoElement, CSSPseudoElementList

> CSS Typed OM Level 1: CSSStyleValue, StylePropertyMapReadOnly, StylePropertyMap, CSSUnparsedValue, CSSVariableReferenceValue, CSSKeywordValue, CSSNumericValue, CSSUnitValue, CSSMathValue, CSSMathSum, CSSMathProduct, CSSMathNegate, CSSMathInvert, CSSMathMin, CSSMathMax, CSSNumericArray, CSSTransformValue, CSSTransformComponent, CSSTranslation, CSSRotation, CSSScale, CSSSkew, CSSPerspective, CSSMatrixComponent, CSSPositionValue, CSSResourceValue, CSSImageValue, CSSURLImageValue, CSSFontFaceValue

**Comment by csnardi** [comment]
I believe this was fixed by #1749 and #2345.

**Comment by annevk** [comment]
Was web-platform-tests updated too?

**Comment by annevk** [comment]
Cool, let's close this then. Guess follow-ups can be filed if any are still missing.
