### ISSUE TITLE
[css-fonts] `system-ui` behavior is undesired for some users

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#3658]
From [crbug.com/554590#c21](http://554590#c21), github, Bootstrap, and Wikipedia decided to stop using the `system-ui` font family because the visual quality of their pages is suffered on some OS/language combinations.

Context reported in the issue above:
- GitHub, https://infinnie.github.io/blog/2017/systemui.html
- Bootstrap, https://github.com/twbs/bootstrap/pull/22377
- Wikipedia, https://github.com/wikimedia/wikimedia-ui-base/commit/c75852427a

**Comment by litherum** [comment]
One of two things is true:

1. The Windows system font really is terrible in some situations
2. The browser implementation of the system font doesn't match the platform

**Comment by Malvoz** [comment]
Why is this a CSSWG issue? 

The blog post mentions a couple of things:

> It turns out that the value of `system-ui` in fact not only depends on the version of the current OS [...]

Why would one expect all OS versions to render the same font?

> It could be good to use the OS font to provide the user with a native look and feel, but on Windows, the font family used for UI changes with the language it is in, as well as the theme used.

> [...] on Windows 8.1/Windows 10 in Simplified Chinese, the system-ui font family evaluates to Microsoft YaHei UI, which, it turns out, not only lacks many font weights that Segoe UI has (say semibold), but has letters and numbers a little larger and bolder to match the Chinese text than what could have been designed with.

Not all fonts support all languages, this is an issue with the rendered font.

> On Windows Vista/Windows 7 and corresponding Windows Server versions, with the Windows Classic theme turned on, one might see the good decades-old Tahoma/SimSun/PMingLiU… for system-ui to evaluate to (replicated on Windows Server 2008 R2 in Simplified Chinese).

Meaning that `system-ui` is not supported?

**Comment by kojiishi** [comment]
I guess we need to solve this when we add more system font families.

@litherum 
> One of two things is true:
> 1. The Windows system font really is terrible in some situations
> 2. The browser implementation of the system font doesn't match the platform

I’m afraid I don’t understand what you’re suggesting. Can you please expand? I agree 1 is true. I’m not sure what 2 means, and I’m not sure what you suggest from these two.

@Malvoz
> Why is this a CSSWG issue? Does the spec need clarification or is this a suggestion for deprecation?

One of the original motivations of `system-ui` is to deprecate non-standard vendor-specific values (`-apple-system` and `BlinkMacSystemFont`) and we thought what the [spec](https://drafts.csswg.org/css-fonts-4/#system-ui-def) currently defines can help it:
> This generic font family lets text render with the default user interface font on the platform on which the UA is running.

However, github, medium, bootstrap, and wikipedia considered that this definition isn’t what they want for Chinese Windows, and that they’re back to the vendor-specific values because they provide what they want. True that this is Windows specific problem, but if people stops using `system-ui` and stick to non-standard values due to the problem, isn’t it our failure?

Blink can fix this. I’m hoping to solve this somehow, make `system-ui` usable, and deprecate our vendor-specific value. But 1) I wanted to note that it will no longer “the default UI fonts on the platform” in some cases, and 2) I would like to sync with other browsers on Windows. /cc @atanassov @emilio

**Comment by AmeliaBR** [comment]
Koji, what particular change are you requesting for the CSS definition of `system-ui`?

In general, I think user agents should have flexibility to select the font(s) to use, even if it doesn't always match the System UI.  And we already have [text in Fonts 4](https://drafts.csswg.org/css-fonts-4/#generic-font-families) allowing the generic font keywords to map to composite fonts that consist of different fonts for different languages.  But, if cross-browser consistency on a given platform is important, then we might need stricter guidance than that.

**Comment by litherum** [comment]
If the Windows system font really is ugly in Chinese, what do Chinese native apps do?

**Comment by kojiishi** [comment]
> If the Windows system font really is ugly in Chinese, what do Chinese native apps do?

They just live with the fonts. The difference is that, those apps are in Chinese and that no other choices are available to render Chinese characters. On the other hand, they were seeing much better fonts when they visit github and other English content sites. But with `system-ui`, all such contents were downgraded to the Chinese fonts too.

Japanese is in similar situation, and I was under impression that users/authors prefer native fonts, even though it looks worse. The feedback revealed that I was wrong. They preferred English system fonts, no matter which language their platform is in, at least for English contents.

We probably need to hard-code the name of English system fonts, and pick it instead of the actual default UI fonts under some conditions. I haven't finalized the exact heuristic yet, I'll think about it more.

> In general, I think user agents should have flexibility to select the font(s) to use, even if it doesn't always match the System UI.

Oh, really, great if so, thank you. The [definition of `system-ui`](https://drafts.csswg.org/css-fonts-4/#system-ui-def) didn't read so to me, but my English isn't great, so I trust your reading.

If the spec text already allows UA to pick other arbitrary fonts than "the default user interface font on the platform", this might not be a spec issue. I can investigate how to make authors happy, and may sync with @atanassov and @emilio outside the WG.

**Comment by GrimLink** [comment]
I still find it stupid that we remove `system-ui` from the font stack instead just moving `Segoe UI` before it.

**Comment by NightFurySL2001** [comment]
I would argue that the current implementation of `system-ui` is on point and should be kept that way; the issue pointed out by https://infinnie.github.io/blog/2017/systemui.html is a non-issue.

> On Windows Vista/Windows 7 and corresponding Windows Server versions, with the Windows Classic theme turned on, one might see the good decades-old Tahoma/SimSun/PMingLiU… for system-ui to evaluate to (replicated on Windows Server 2008 R2 in Simplified Chinese).

What this section missed ***in context*** is that, the *system font itself* is also changed (to the uglier but clearer bitmap font, which is SimSun for Simplified Chinese system) when the theme changed, so what `system-ui` evaluates to be _does_ indeed match the current system font. The following provides screenshots for the actual Windows 7 system, please notice the font used by the file names on the desktop and Windows Explorer.

Windows 7 Aero theme, using Microsoft YaHei:
![Aero theme](https://user-images.githubusercontent.com/33471049/133435080-9af8c691-8eb8-447e-b59f-89c632ed0ed2.png)
Windows 7 Classic theme, using SimSun:
![Classic theme](https://user-images.githubusercontent.com/33471049/133435089-b9af98d7-65ce-426d-b965-4b09e2c7911b.png)

<details>
  <summary>`index.html` source code</summary>

```html
<html>
<style>
body{
font-family: system-ui;
}
</style>
<body>
Testing text using <code>system-ui</code>. This page is displayed with Google Chrome.
</body>
</html>
```

</details>

This is an "issue" with Windows rendering engine, not with the CSS specs. Display for CJK (and corresponding Latin text in their languages) has been using bitmap fonts for a long time, and in places where clarity is required, using bitmap font is better than using newer system fonts (considering there is still a relatively large CRT moniter user group in China).

> If the Windows system font really is ugly in Chinese, what do Chinese native apps do?

On Windows 7 and earlier, there are two ways:
1. keep the original system font (or don't specify in software), which uses SimSun ***if using the Classic theme***
2. hardcode the new system font (Microsoft YaHei) in software, which will not change when changing theme

I am unable to test on Windows 8 and later due to single display language pack limitation, but I would guess the High Contrast settings might result in the same behaviour (Chinese font reverted to bitmap font, i.e. SimSun/PMingLiU for high contrast theme for display clarity).

Do be noted that this "issue" only arises when the user *voluntarily* choose to use the Classic theme (Windows 7 & lower)/High Contrast settings (Windows 8 & higher), which is a correct response as the user might intend to use the theme/settings for their individual requirements. We as developer should in no way work against the choices users had made, even though it might look worse for us (but not them).

Thus, my conclusion is:
**1. The Windows system font really is terrible in some situations**, but intended. There is no reason to stop using/implementing `system-ui`, and with Firefox adding support in August 2021 (https://github.com/mdn/content/issues/7751), there is literally nothing stopping the usage of `system-ui`.

**Comment by fireattack** [comment]
It's not just the SimSun being terrible; MS YaHei is also terrible for displaying Latin characters (among lots of other things, like Japanese Kana), which was why as mentioned above, GitHub, Bootstrap, Wikipedia, and later Stack Overflow, all had to roll back from using it due backslash from the community. 

Go and add `system-ui` in CSS on GitHub to your Chinese Windows VM and check this very page again to see how it looks.

Is it "intended"? Yes it is. But in the ideal world the intended use should give somewhat good result. It doesn't matter which end is causing the issue, at the end the website designer is the one have to deal with it.

>There is no reason to stop using/implementing system-ui

If you as a dev care about (Chinese) Windows users, you should think twice about using system-ui font. Plenty of Chinese users read English websites. And keep in mind it is a "regression" in term of user experience. The current stack of `-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji"` can at least generate good result for these users (without sacrificing other users).

**Comment by NightFurySL2001** [comment]
@fireattack The Latin characters in Microsoft YaHei comes from Segoe UI (of Windows 7), just slightly enlarged. I don't think it looks terrible; in fact, comparing it to the original Segoe UI it is way more legible due to its increased font size.

For the benefit of doubt, I have also tried out Traditional Chinese (Microsoft JhengHei) which also is based on Segoe UI. It did not make too much of a difference too. Both Chinese variants only had "issue" when using Windows 7 Classic theme.

Following are attached screenshots from my Windows 7 work machine, with UI language English, Simplified Chinese and Traditional Chinese, all 3 presented using both Aero theme and Classic theme:

<details>
  <summary>Expand for screenshot</summary>

## English
### Aero
Evals to Segoe UI.
![en-aero](https://user-images.githubusercontent.com/33471049/192552691-3592c772-1b4f-4a59-9995-578872e46f1b.png)
### Classic
Evals to Tahoma.
![en-classic](https://user-images.githubusercontent.com/33471049/192552716-2759f4f8-96fd-4fb4-80f3-1bf44e435baf.png)
## Simplified Chinese
### Aero
Evals to Microsoft YaHei.
![zhs-aero](https://user-images.githubusercontent.com/33471049/192552935-6830ec66-4c0b-4dbf-8a42-9d012f2d89b0.png)
### Classic
Evals to SimSun.
![zhs-classic](https://user-images.githubusercontent.com/33471049/192552940-e892fe1a-7094-468c-964d-8517c7145891.png)
## Traditional Chinese
### Aero
Evals to Microsoft JhengHei.
![zht-aero](https://user-images.githubusercontent.com/33471049/192552945-a6930d49-11bf-409c-9278-cb4a66780400.png)
### Classic
Evals to PMingLiU.
![zht-classic](https://user-images.githubusercontent.com/33471049/192552949-5dbd3840-7624-43e1-bb0e-e3a8734fac24.png)

</details>

> GitHub, Bootstrap, Wikipedia, and later Stack Overflow, all had to roll back from using it due backslash from the community.

Please note: most of these sites changes reference the only one "issue" regarding `system-ui`: https://infinnie.github.io/blog/2017/systemui.html on GitHub ([Bootstrap [note that the issue author is the same as the blog post author - conflict on interest]](https://github.com/twbs/bootstrap/issues/22328), [Wikipedia](https://phabricator.wikimedia.org/T175877#4776576)), which only "affects" Simplified Chinese, Classic theme, Windows 7 users. It should be in no way that such a minority group should be allowed to direct most of the users to stop using `system-ui` just because the font rendering is bad for their language in one old settings, ignoring all the other benefits of using `system-ui`. 

> Is it "intended"? Yes it is. But in the ideal world the intended use should give somewhat good result. It doesn't matter which end is causing the issue, at the end the website designer is the one who has to deal with it.

Please note that what `system-ui` is *not* for giving good result, it is to **integrate with the look and feel of the native OS** (https://drafts.csswg.org/css-fonts-4/#system-ui-def). It is just faithfully reproducing what the user had already been using on their native OS, regardless of the font choice. If the designer doesn't like it, do stop using `system-ui`, but they're just missing on the chance to localize to the users correctly.

> And keep in mind it is a "regression" in term of user experience. The current stack of `-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji"` can at least generate good result (Segoe UI) for these users (without sacrificing other users).

Do note that this will make Windows 7 *Classic* theme (pointed in ["the issue"](https://infinnie.github.io/blog/2017/systemui.html)) display the wrong font: it should have been Tahoma, not Segoe UI.

---

When I was in discussion with GitHub when they naively added Meiryo to the font stack (overriding Chinese text too), the devs have mentioned that they would very much like to use `system-ui`, [including if the user chose to use a serif font](https://github.com/primer/css/issues/1209#issuecomment-770645331), but is blocked only due to "the issue". Quote:

>> Why prioritise system-ui over ui-sans-serif? If the system is using, say, a serif font as the system font, would Primer really want to use that?
>
> AFAIK, Primer tries to stay as close to the default system font as possible. So I would say yes.

---

Mentioed in https://infinnie.github.io/blog/2017/systemui.html:

> the `system-ui` font family evaluates to Microsoft YaHei UI, which, it turns out, not only lacks many font weights that Segoe UI has (say semibold), but has letters and numbers a little larger and bolder to match the Chinese text than what could have been designed with

I acknowledge that this is an issue on Windows, but do note that this issue also affect other languages and system too. 

On Windows, Traditional Chinese uses Microsoft JhengHei, which has an even worse Bold weight compared to Simplified Chinese Microsoft YaHei. Both Chinese fonts come with 3 weight: Light, Regular, Bold. Following is a rough font weight comparison for both Chinese fonts (hanzi only) relative to Segoe UI (italic are new weights not in Windows 7):

![image](https://user-images.githubusercontent.com/33471049/192567649-ca98781e-1c11-4d2f-922f-acfd42d7a11c.png)

Meiryo for Japanese isn't anywhere good; it only have 2 weights: Regular and Bold.

On Mac side of things, the Chinese font PingFang comes in Simplified Chinese (China), Traditional Chinese (Taiwan), and Traditional Chinese (Hong Kong), each comes with 6 weights. However, the weights provided are ([source](https://support.apple.com/en-my/HT212587) [(2)](http://www.itfanr.cc/2020/12/23/pingfangsc-and-flutter-fontweight/)): 

中文 | 英文 | FontWeight值
-- | -- | --
苹方-简 极细体 | PingFangSC-Ultralight | w100
苹方-简 纤细体 | PingFangSC-Thin | w200
苹方-简 细体 | PingFangSC-Light | w300
苹方-简 常规体 | PingFangSC-Regular | w400 or normal
苹方-简 中黑体 | PingFangSC-Medium | w500
苹方-简 中粗体 | PingFangSC-Semibold | w600

Its Semibold isn't even reaching Bold weight of SF Pro.

Only Japanese text is remotely good on Mac: Hiragino Sans comes with W0-W9, matching closely with SF Pro's weights.

It's way better on Android (and some Linux) side: Noto Sans CJK comes with 7 weights, roughly matching Roboto's 6 weights. Also, all CJK regions uses the same font design, which is a plus when using `system-ui` since there is no discrepency between different localization.

Point is, CJK fonts have been quite a pain on system vendors due to its pricey nature. "lacking many font weights" is definitely not a factor when considering a design to match user's system: there's only that many weights on all these OS, and OS fonts are limited to the same set of weights too. The burden of `system-ui` being "ugly" is on OS vendor on this issue. Website developers will be better off hard coding the best font for their own locale (which might be an issue; see next point) instead of relying on `system-ui` if they want a "good result".

---

Also, there is additional benefits such as correctly localizing the font for the users, especially towards CJK users. Let me demonstrate: the following is a text typesetted in Microsoft YaHei (SC), Microsoft JhengHei (TC), Meiryo (JP):

![image](https://user-images.githubusercontent.com/33471049/192560163-1f72abce-49bc-47fb-90aa-4480b684fa88.png)

Notice the following characters: `将`, `甩`, `复`, `与`, `窗`. These characters are written differently in different languages/regions due to an issue: [Han unification](https://en.wikipedia.org/wiki/Han_unification). By using `system-ui` and correct user localization settings (which most Chinese users do), this above issue is mitigated by using the correct font stack to display CJK Unified Ideographs, and preventing display of incorrect localization. Using `sans-serif` does not come with this benefit as it uses the *default* font fallback regardless of system locale settings, which on Windows prioritise Japanese over Chinese and leading to more issues than of broken Latin text. Hard-coding the font stack will only work if you're targeting one specific locale, as you will be required to order the priority of fonts.

The locale settings in `system-ui` doesn't only help CJK, it might help with other locales too (e.g. [different italic forms of Cyrillic](https://russian.stackexchange.com/questions/1552/why-does-italic-%D1%82-look-like-m)). As I said, no reason to stop using `system-ui` for just some ugly display due to poor user (and system font) choice.

*Ignore this point if your website has correct language tagging: `<html lang="zh-hans">`/`zh-hant`/`ja` will fix the font for `sans-serif` most of the time. If your (or user-generated) content does not have any language information, `system-ui` is the better bet for localization.*

---

TL;DR: **The issue mentioned in https://infinnie.github.io/blog/2017/systemui.html is a non-issue as it isn't what `system-ui` tries to achive: providing the native OS feel that the user already had on their machine.**

**Comment by fireattack** [comment]
@NightFurySL2001 

I'm aware the other aspects of this issue as you mentioned, and I'm pretty sure OP being an expert in CJK field, knows it better than both of us. But let's back the topic: I don't agree with you that MS YaHei is "not terrible"; it's too wide compared to majority of English typefaces. 

Regardless, it being "enlarged" alone is already a serious drawback since the designers of the sites often have a fixed (perceptive) font size in their mind. Let's put it this way: if English users see the font in that size is expected, why Chinese users (when *seeing the same English content*) would need something different?

> Using `sans-serif` does not come with this benefit as it uses the default font fallback regardless of system locale settings, which on Windows prioritise Japanese over Chinese and leading to more issues than of broken Latin text. 

Totally false. Did you even test it? Firefox and Chrome have slightly different fallback mechanics [1] in this regard, but both will fallback to Chinese version glyphs on a Chinese Windows. It even works with Chinese Windows with browsers in English display language. 

Chrome: 
![image](https://user-images.githubusercontent.com/4130991/192632135-9dd1a71e-d3c3-43a6-b4dd-534d097ab094.png)
Firefox:
![image](https://user-images.githubusercontent.com/4130991/192632265-689bc512-1b75-414e-a9ca-826ce7e8e1d5.png)

Chrome is even better when using `sans-serif`, because it uses Meiryo to display kanas. Firefox on the other hand, will use heuristics to guess the language of un-tagged content and use that for the whole page instead, it is not a glyph-by-glyph process.

<details>
  <summary>Footnote</summary>

[1] On chrome, make sure you set Chinese priority higher than Japanese. Which is the default if you use Chinese version Chrome.
![image](https://user-images.githubusercontent.com/4130991/192632440-4e878140-d5fc-4e63-911a-b4eadac7c486.png)
</details>

> Ignore this point if your website has correct language tagging: <html lang="zh-hans">/zh-hant/ja will fix the font for sans-serif most of the time. If your (or user-generated) content does not have any language information, system-ui is the better bet for localization.

Funny you mentioned lang tagging. This is one of THE worst issue of system-ui, actually, other than being ugly. 

*Even if you tag it with `<lang="ja>`*, it will still use MS YaHei font if you use system-ui. See the screenshots above.

**Comment by NightFurySL2001** [comment]
> But let's go back the topic: I don't agree with you that MS YaHei is "not terrible"; it's too wide compared to majority of English typefaces. 

Have you seen Tahoma for Windows 7 Classic theme (screenshot provided in previous comments)? It is wider and higher than Segoe UI, but users does not have a problem with it. What you are trying to do now is you are forcing people to follow *your own aesthetic standards* by saying the font is too wide compared to Segoe UI and ignoring all the other benefits of `system-ui`.

> Also some punctuations are totally ruined:

This is non-issue: The font being used is compliant to GB 18030, which makes the quotation mark full-width as it is used in Chinese for quotation (E.g. `“我觉得：‘你觉得’。”`) This is a legacy problem related to the decisions of GB team and Unicode to share a codepoint for quotation marks. Font support (in Microsoft YaHei) from its vendor Microsoft is required to fix this "problem", and not a problem of `system-ui`.

> Regardless, it being "enlarged" alone is already a serious drawback since the designers of the sites often have a fixed (perceptive) font size in their mind. Let's put it this way: if English users see the font in that size is expected, why Chinese users (when seeing the same English content) would need something different?

If you are designing for cross-platform, multilingual use, a "fixed (perceptive) font size" is a *very* bad decision. Some languages requires bigger line height/size to accommodate their respective languages, which sometimes reflects on to the fonts being used. It is better to use the designated font (and size) provided by the system for each language rather than trying to enforcing a constant aesthetic across all language groups.

If the system vendor does not think enlarging text is required (eg in Mac), *then* that will fit your usage. Else, just write your own font stack.

> Totally false. Did you test it? Firefox and Chrome have slightly different fallback mechanics [1] in this regard, but both will fallback to Chinese version glyphs on a Chinese Windows. 

Sorry, this is my fault. I did not test this issue thoroughly.

> It even works with Chinese Windows with browsers in English display language.

> Even if you tag it with <lang="ja">, it will still use MS YaHei font if you use system-ui. See the screenshots above.

However, I failed to recreate this issue. `system-ui` with language tagging works just fine on pure English Windows. Screenshot below (latest stable Chrome & Firefox):

![en-user](https://user-images.githubusercontent.com/33471049/192789626-b56847b4-5934-40c2-a922-113f9ffe6441.png)
![en-user-firefox](https://user-images.githubusercontent.com/33471049/192789631-bec8b302-084d-4c3b-8db8-278c2b2e952e.png)

This is an issue with Windows multilingual and should be raised to Microsoft. However, this alone shouldn't be an issue to block websites from using `system-ui` as the issue is vendor-specific. The testing works fine on Android and iPadOS, with respective correct locale display, and even better display of Latin text using Roboto (both using Simplified Chinese UI):

<details>
  <summary>Screenshot of lang on Android and iPadOS</summary>

![image](https://user-images.githubusercontent.com/33471049/192778605-729618b4-8e0c-495f-a140-ad5085ba26ef.png)
![image](https://user-images.githubusercontent.com/33471049/192778769-c56673a4-2f0d-43b3-8ca4-5319c3302919.png)

</details>

Also, I will argue that displaying the *correct localization with correct font* **when no language tag is present** is more important than displaying the *best visual result* when no language tagging is done. You definitely do not want Meiryo to overrride the Chinese part (especially by default, Meiryo is overriding Microsoft YaHei in regedit) as most of the internet *does not tag languages properly* (e.g. GitHub user content). Using `system-ui` will ensure the correct locale is displayed based on system settings.

> Also, system-ui is intrusive. If I don't like X font, I can always manually replace it with

`system-ui` is *not* designed to be replaced. It is just a keyword that is used to replace Mac's hacky `-apple-system,BlinkMacSystemFont` font stack while expanding the same functionality across platform, such that developers can integrate their website *using the system font*. For the screenshot provided in ["the issue"](https://infinnie.github.io/blog/2017/systemui.html) by infinnie, remember, this is what the system font has already been using.

## English
### Aero theme
![en-aero-font](https://user-images.githubusercontent.com/33471049/192782798-ff30bfb8-498d-4b1f-a408-fe875d4ab8db.png)
### Classic theme
![en-classic-font](https://user-images.githubusercontent.com/33471049/192782821-d777bd6e-4ef2-470a-b97d-286be8f9fc4e.png)

## Simplified Chinese
### Aero theme
![zh-aero-font](https://user-images.githubusercontent.com/33471049/192782845-b52bedce-9118-4ef0-b1c7-da5dd10a215f.png)
### Classic theme
![zh-classic-font](https://user-images.githubusercontent.com/33471049/192782853-b796d611-56ce-4a31-81c5-858c02fa860d.png)


There is no point to replace `system-ui` for something *you* want instead of what its intended purpose is. If you don't like it, write your own global CSS with `!important` keyword to always replace the site font.

> At last, a more general point: https://infinnie.github.io/blog/2017/systemui.html is not the holy grail of system-ui issue. Refuting that alone doesn't mean all issues are non-issue. As I displayed above, the issue of it isn't limited to "niche, classic theme" users.

Please note, *all* issues I have been looking on `system-ui` ([StackOverflow](), and including your issue) points to this specific target group: Windows, Simplified Chinese users; literally no other languages have any related kind of issues.

TL;DR: **`system-ui` is for using the current system font. Locale tagging might be broken for some languages, however all texts will be displayed by the user's preferred locale first instead of relying on prewritten font stack. Some fonts for specific locale (most notably Simplified Chinese) will be bad in some particular instances; in other languages it will be enough for normal daily usage.**

Side note: Windows has always been bad on multilingual display; Win32 doesn't even handle multilingual text in the same line. That is the main point why this "issue" is being brought up in the first place from Simplified Chinese users (bad Latin in SimSun from Windows 95-XP, "wide" Latin in Microsoft YaHei from Windows Vista-11). However, there is no way that this should be the point that *all* sites **must** stop using `system-ui`, and CSS should drop support for `system-ui`. It is a great tool for devs to use, and if you can't handle it, do write your own font stack; just please dont shove your opinion through all other user's throat. The most minimal fix that does not affect other users should be contacting Microsoft and let them fix it (e.g. WinUI), rather than blocking all other global users from using `system-ui`.

**Comment by myakura** [comment]
> Please note, _all_ issues I have been looking on `system-ui` (StackOverflow, and including your issue) points to this specific target group: Windows, Simplified Chinese users; literally no other languages have any related kind of issues.

Well, `system-ui` isn't great on Japanese Windows either. Yu Gothic UI, the font which is resolved when `system-ui` is used on Windows (10+), looks like a condensed typeface thus is not great when used in paragraphs. People complained when GitHub added `system-ui` to their theme so they tweaked their CSS to add Meiryo for readability https://github.com/primer/css/pull/1573 .

I really wish people use `sans-serif` (or `serif`) instead of `system-ui`; `system-ui` takes away users' ability to customize fonts in browser settings...

**Comment by NightFurySL2001** [comment]
That is still a problem with Microsoft and bad font choices, along with bad Win32 font technology. Please report the problem to Microsoft. (Same for customization: report the bug to system vendors; not a problem from CSS specs)

If `system-ui` is so bad, what alternatives do you suggest for replacing the lengthy `-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji"` (and even longer if considering Android, also bad display of Arial on *nix systems) to achive the same goal: ["integrate with the look and feel of the native OS"](https://drafts.csswg.org/css-fonts-4/#system-ui-def)? If this goal not suitable to be achived, what goal should `system-ui` do?

**Comment by fireattack** [comment]
You keep saying actual, practical issues are "non-issue" because "that's what MS should fix", "that's what XXX should fix", that's a frustrating way to constructively discuss anything.

> This is non-issue .... This is a legacy problem 
> Font support (in Microsoft YaHei) from its vendor Microsoft is required to fix this "problem", and not a problem of system-ui.

The full-width curly quotes isn't an issue of MS YaHei, which is supposed to be a Chinese font. It's totally fine for it to have full-width quotes. The issue is you force to use MSYH on pure English content, which is what system-ui on Chinese Windows does. 

> If you are designing for ... multilingual use,

I'm literally taking about the issue of `system-ui` caused on English-only or English-majority content.

> However, I failed to recreate this issue. system-ui with language tagging works just fine on pure English Windows.

???? The whole discussion is about issues of `system-ui` for Chinese Windows (or Japanese Windows) and now you test on English Windows? 

Of course it doesn't happen with English Windows, because its "system-ui" is Segoe UI, which don't have CJK glyphs and will fallback to a different Chinese/Japanese fonts for that. The whole point of "system-ui bad" is because on Chinese Windows the default font (MSYH) has too large character set and will be used to display anything, even when improper.

> this alone shouldn't be an issue to block websites from using system-ui as the issue is vendor-specific

Previously you said these are non-issues that shouldn't block because it only affect a small, niche, classic theme users (quote: "Do be noted that this 'issue' only arises when the user voluntarily choose to use the Classic theme"), and I pointed it out it actually affects all the Chinese/Japanese Windows users. And now you moved the goalposts to say "Chinese, Windows users are too small to block".

> Also, I will argue that displaying the correct localization with correct font when no language tag is present is more important than displaying the best visual result when no language tagging is done. You definitely do not want Meiryo to overrride the Chinese part
> by default, Meiryo is overriding Microsoft YaHei in regedit

I already said, will example, if you use `sans-serif`, this won't very happen. Chrome will pick characters based on the priority of your locale setting. Even if you're using English Windows. Your screenshot confirms it. Not sure how it has anything to do with regedit. Go ahead and change your language priority in Chrome. You will see changes immediately in real-time: 

![image](https://user-images.githubusercontent.com/4130991/192898034-81232261-7eb3-402c-a473-3d08c703ff98.png)
Result (remember to refresh): 
![image](https://user-images.githubusercontent.com/4130991/192898124-36ea40db-24d5-443c-bce0-0045cdd05537.png)

![image](https://user-images.githubusercontent.com/4130991/192898173-ac4b7e1b-0533-40fd-b5ae-450736c2eb63.png)
Result (remember to refresh): 
![image](https://user-images.githubusercontent.com/4130991/192898195-0d848bc9-971e-4cde-9adb-e91a94e9f41c.png)

This problem actually WILL happen, in a different way, when you use `system-ui` in CJK Windows. If you use Japanese Windows + `system-ui`, Meiryo WILL override Chinese part (as soon as it has these glyphs)`, just like if you use Chinese Windows MS Yahei WILL overwrite Kana part). 

> Using system-ui will ensure the correct locale is displayed based on system settings

Again, totally false. And this point, I feel like you don't know, or have thoroughly tested, how `system-ui` or font fallback works. Since you use Chrome, here is how it works in Chrome:

* `system-ui` works by simply applying MSYH (Simp. Chinese), Yu Gothic UI or Meiryo (Japanese), or Segoe UI (English) to all the content, regardless if here is language tag or not.
* `sans-serif` on the other hand is language-aware. It uses the sans-serif font in corresponding settings for each language if lang tag is set. By default, if you use `sans-serif` + lang=hans, it will apply MSYH to all the content. Same goes to other languages. 
* If a character does not exist in the given font, it will fallback to a bigger set. 
* For ambiguous cases (like 将/甩) Chrome will prioritize what the users prefers based on language settings. 

The problem with `system-ui` on Chinese Windows is, MSYH have all the glyphs. Once it is set, it will override virtually everything, language tagged or not. This won't happen if you are using English Windows, because its system-ui font doesn't have CJK characters. It won't happen if you just use `sans-serif` instead, either.

The issue that "on English Windows, untagged content will use Meiryo to display Chinese characters instead of MSYH" you mentioned is because the locale isn't properly set. So Chrome have nothing to work with, and it picks Japanese over Chinese. This can be easily fixed by making sure Chinese locale has higher priority than Japanese, as said above.

You don't need system-ui to 'fix' this: because on English Windows all it does is just to apply Segoe UI on all the content and then it relies on font fallback to do the reset of the job. The same can be archived by using any English font - like `sans-serif` (which isn't a real font, but it will use Arial).

TL;DR: `system-ui` isn't what fixed your "Chinese characters in Meiryo" issue. And it causes all the other issues on Chinese and Japanese Windows simultaneously. 

> There is no point to replace system-ui for something you want

I.. what?

> all sites must stop using system-ui, 
> CSS should drop support for system-ui

No one is suggesting any of these. 

> shove your opinion through all other user's throat

No one is doing that, either. All the websites listed above are too big to not deal with `system-ui`'s drawbacks, because they have sizable Chinese users. Which is exactly why they "do write your own font stack" as you suggested. 

> If system-ui is so bad, what alternatives do you suggest for replacing

Just use `sans-serif`? Or even just stick with this long mess. Yes it sucks `system-ui` didn't magically work in all cases but that's the reality.

**Comment by fireattack** [comment]
@NightFurySL2001 MSYH's Latin characters are not "bad" on per letter level. It just doesn't suit for displaying English-only or English-majority content due to dramatic size difference and punctuation issues. Same goes to Meiryo, just worse. 

>  SF Pro on Mac have slightly higher x-height compared to Segoe UI, and on the same screen SF Pro appears larger than Segoe UI too just like Microsoft YaHei

Some quantitative comparisons might help. How "larger" is it? Just as large as MSYH?

>  Does it make sense when Japanese users say that Meiryo looks better than Yu Gothic UI, when you are saying that Microsoft YaHei looks worse than Segoe UI?

Sorry, I genuinely don't get what you mean. I think Segoe UI is better than MSYH, yes. I also think (based on your image, I'm not familiar with Yu Gothic UI) Yu Gothic UI ('s latin part) is better than Meiryo's. Because both former ones are more compact. Is it supposed to be some contradictions here?

> What do you suggest the W3C CSS working group to do with system-ui

Nothing. I didn't open this issue, or even replied here before your comment. I do agree with https://github.com/w3c/csswg-drafts/issues/3658#issuecomment-512514812.

My comments elsewhere, are meant to warn people who care about user experience than some purist ideology, to think twice before *using* system-ui due to its issues. pretty much everything I said have already been said by .  

And while I am flattered you thought that way, I'm not the only one who expressed the opinion on this matter to "block" changes. I didn't even involve in the discussions that eventually caused GitHub/Wikipedia/Bootstrap to roll back their changes. I did make comments "in time" on SO's case IIRC, but I'm far from the only one (and lots of English users seem to have issues with system-ui on other platforms too, but I am not familiar with that enough to comment).

**Comment by NightFurySL2001** [comment]
> Some quantitative comparisons might help. How "larger" is it? Just as large as MSYH?

SF Pro (Text) is not as large as Microsoft YaHei, but comparable to Tahoma. For numerical sense, the x-height are: Segoe UI 1024, SF Pro 1078, Tahoma 1117, Microsoft YaHei 1106. Caps height are: Segoe UI 1434, SF Pro 1443, Tahoma 1489, Microsoft YaHei 1549. Ascender heights are: Segoe UI 1516, SF Pro 1506, Tahoma 1556, Microsoft YaHei 1637.

Compared to Segoe UI, Microsoft YaHei is geometrically scaled up 108%, ratio between x-height and ascender is same as Segoe UI (67.5%). SF Pro x-height is 5% larger than Segoe UI while other metrics are relatively same as Segoe UI; ratio of x-height to ascender is 71.5%. Tahoma x-height is 9% larger than Segoe UI, and slightly bigger than Segoe UI in general by ~1%; ratio of x-height to ascneder is 71.8%. (Ratio of x-height to ascender usually determines the visual size of a font, i.e. the ratio of height of `x` compared to ratio of height of `l`)

> It just doesn't suit for displaying English-only or English-majority content due to dramatic size difference and punctuation issues.

The scaling on Microsoft YaHei is actually done to make it harmonize to Chinese parts; there are some generic metrics used in Chinese (and Japanese) fonts and those metrics usually requires the Latin part to be scaled up to make it visually harmonize. Reference: [Noto Sans CJK/Source Han's Latin part is scaled 113-115%](https://ccjktype.fonts.adobe.com/2015/01/shs-vs-ssp-and-scp.html), [Adobe Clean at 105-116%](https://ccjktype.fonts.adobe.com/2016/10/a-new-face-for-adobe-redux.html), [IBM Plex JP at 105%](https://github.com/IBM/plex/issues/388). As I said, there is nothing wrong inherently by scaling the Latin part up in CJK fonts.

> I also think (based on your image, I'm not familiar with Yu Gothic UI) Yu Gothic UI ('s latin part) is better than Meiryo's, so if Japanese users tell me that, I will agree with them. Because both former ones are more compact. 

Please read my comment (which you quoted) carefully: Japanese users prefer Meiryo over Yu Gothic UI. [See @ myakura comment here](https://github.com/w3c/csswg-drafts/issues/3658#issuecomment-1260957890) or [this twitter thread, quoted below](https://twitter.com/448jp/status/1432196177747873793):

> system-uiは文字通りUIのフォントを指定するためのもので、本文にはまったく向いていません。
> Google translate: Before I knew it, system-ui was added to GitHub's font-family specification, but on Windows it's displayed as Yu Gothic UI and it's hard to read, so I really want you to stop it.

> So lets make it clear before we continue to argue semantics: do you genuinely think this: [...] is better than this: [...]?

Yes. The design of Segoe UI is actually towards the smaller size (smaller x-height:ascender ratio), in this case Microsoft YaHei (UI)'s scaling up is more suitable and have better legibility. Here are a few screenshot using other fonts:

Segoe UI
![image](https://user-images.githubusercontent.com/33471049/193171942-97ec45e4-94cf-4fc7-8c25-dcaa1107f6b7.png)

SF Pro Text
![image](https://user-images.githubusercontent.com/33471049/193171961-8ffa10d2-8b58-4135-80c4-6daf55dc4d4f.png)

Tahoma
![image](https://user-images.githubusercontent.com/33471049/193171974-701f35c8-a592-4a17-8912-c238cc01b955.png)

However, I do have to mention that I usually use my own CSS rule to override the webpage fonts, and I'm using [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) which also has a larger size compared to Segoe UI.

**Comment by fireattack** [comment]
I'm sorry, but why did you constantly compare to Tahoma? Isn't it only used by "classic theme" users, an actual niche group you think we should just ignore all together (I'd say less than 1%, but I pull the number out of my ass) ?

> Japanese users prefer Meiryo over Yu Gothic UI. https://github.com/w3c/csswg-drafts/issues/3658#issuecomment-1260957890 or [this twitter thread, quoted below](https://twitter.com/448jp/status/1432196177747873793):

That's because Yu Gothic UI's JAPANESE part is worse (subjectively, obivously). Not Latin part...

> Here are a few screenshot 

Can you please at least screenshot in 100% zoom? All the fonts in your images are blurry (and it's not because of DPI setting).

**Comment by NightFurySL2001** [comment]
Sorry for unclear screenshot. I will use another software and replaced the above screenshots with additional screenshots for Japanese fonts.

> The font on GitHub IS small. 14px.

That is the point. Given the same font size, larger visual font *will* provide better legibility. That is merely a fact.

> You are wasting time arguing something that didn't even affect you with people who actually have to suffer this. And if I understand it right, you don't even use Chinese Windows to begin with

That is because `sans-serif` produce undesirable effect *for me*. `sans-serif` fallbacks to SimSun on my primary machine on Chrome for Chinese text for unknown reasons, and it definitely looks worse. Using `system-ui` does fix it for me but I could not reproduce the issue on other machine, so I just opt for overriding CSS with Latin parts from Sarasa Gothic and `system-ui` for the rest. Also, what you're saying still is still a problem with *aesthetics* that "Microsoft YaHei looks bad", which will differ from person to person. I could not comment on Yu Gothic UI's case. 

My point is, `system-ui` is in working order, and W3C shoud not do anything. If devs *want* to use `system-ui` to match the user's interface, I don't see any reason to block it.

Just for reference, could you provide any links that anyone else is saying Microsoft YaHei's Latin part looks bad from either English or Chinese communities?

**Comment by fireattack** [comment]
>fallbacks to SimSun on my primary machine on Chrome for Chinese text for unknown reasons

Install https://chrome.google.com/webstore/detail/advanced-font-settings/caclkomlalccbpcdllchkeecicepbmbm?hl=en 
(this is an official extension, it basically just provide a way to adjust corresponding font settings in `Preferences`. You can edit them manually too it's just a JSON file):

![image](https://user-images.githubusercontent.com/4130991/193177466-55c374bf-ad74-4001-958d-f08615ee2c77.png)

MSYH has been the default for sans-serif for years, but it was SimSun at one point. If I have to guess, your issue probably is caused by an old profile which inherited such settings from previous installs.

> Just for reference, could you provide any links that anyone else

As I clarified above, I meant that they're too big (wide?). Not the glyphs themselves are bad.

**Comment by chris-morgan** [comment]
I say there are two problems here:

- Developers are widely using `system-ui` as a proxy for (subjectively) prettier `sans-serif`, and then getting bitten by the fact that `system-ui` has different *semantics*, and those semantics make it very undesirable for some users. Probably the best solution here is for browsers to update their default sans-serifs to these prettier fonts, and then encourage web developers to go back to just `sans-serif`, and then dissuade developers from using `system-ui` unless that’s *actually* what they want semantically (which it seldom is in online content—I see `system-ui` as being about as niche as system *colours*: useful for installed apps, but almost without valid use on online content).

- `system-ui` interacts poorly with localisation. `sans-serif` is generally implemented as a composite font, resolving to various different fonts for different languages, but I believe (without verifying it) that `system-ui` is *in practice* always implemented as a single font, because that’s how all the main operating systems model it. Thus, `system-ui` is only suitable for use with content that matches the system language (which is something online content fundamentally cannot verify, thus making it presently universally unsuitable for online content except by user opt-in), and you may get unpleasant results if you use it with a different language. But it’s not clear that this should be changed, once you acknowledge that the widespread use of `system-ui` has been almost entirely *ab*use.

So my actual proposal here is:

1. Update non-normative text in the spec to discourage the use of `system-ui` for online content, with explanation;
2. Work with browser makers to improve the fonts `sans-serif` resolves to (so that web developers don’t feel the need to go beyond it);
3. When all this is done, evangelise collapsing the teetering piles of system font stacks down to `sans-serif`. Just `sans-serif` and *nothing* else.

One small part of this is in scope for CSSWG, the rest is largely up to browser makers.

**Comment by Sora2455** [comment]
Anecdotally, I've always seen `system-ui` advertised as "use this keyword so that the user sees the same font as their OS", so I disagree with your first dot point. From my point of view, the problem is your second dot point: that for some versions of windows in some languages (particuarly when the language of the webpage does not match th language of the OS) the font chosen is sub-optimal.

Also judging by [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1226042#c18), `system-ui` is not only a different font per language on Mac OS, but sometimes a different font for different font sizes.

**Comment by chris-morgan** [comment]
OK, macOS is apparently doing a much, much better job of this than I realised. I downgrade “in practice always” to “commonly” (because I think it’s still what every *other* platform does) with the other obvious corresponding wording changes.

As for the first part: it often *starts* as “the same font as their OS”, but this is very consistently “… because `sans-serif` is ugly”. (Then after that it generally becomes cargo-culting.) I don’t believe that “the same font as their OS” is actually what people are generally aiming for, and when they are it’s fairly consistently misguided: and the problems apparent in the second point show that it’s not what they *should* be aiming for, quite apart from the whole obvious thing of the semantic mismatch. If `sans-serif` was improved, people wouldn’t feel the need for something better, and so wouldn’t abuse `system-ui`.

**Comment by mirabilos** [comment]
TIL about `system-ui` and I’m appalled that such a thing even exists. Now researching how to even _set_ that (given I’m under GNU/Linux with no desktop environment, that’s probably going to be hard)…

Please remove this from the spec.

**Comment by tats-u** [comment]
Yu Gothic UI is not suitable for long text. It is _abused_ by some documentation frameworks (e.g. Docusaurus and VitePress) via `system-ui`, but __it is not optimized for long text, which they are designed to serve.__ It is overly optimized for cramming labels or relatively short descriptions into narrow spaces. Hiragana and katakana are too condensed compared to han characters.

Noto Sans JP (`sans-serif`) and Yu Gothic (Medium) provide better reading experience for long text like documentation and blog.
It is difficult to use Yu Gothic Medium in CSS, so I mostly recommend Noto Sans JP via `sans-serif`. There are some Japanese who prefer Meiryo to Noto Sans JP and have specified Meiryo as `sans-serif`, so `sans-serif` can provide the most comfortable experience for reading Japanese text.

`system-ui` is _only_ for web-based _apps_ (including VS Code, draw.io, and other Electron or WebView-based apps) that want to provide a similar appearance to the OS.

For documents and blogs, the order "(Custom Latin fonts (e.g. Inter) >) Apple system font designations > OS Latin fonts (e.g. Segoe UI or Helvetica/Arial) > `sans-serif`" is the best.

**Comment by myakura** [comment]
I wholeheartedly agree with https://github.com/w3c/csswg-drafts/issues/3658#issuecomment-3299209852.

Apart from some typeface design issues, the `system-ui` value ties the typeface to the "system" fonts, which takes ability away from users to customize the typeface to their preference using `sans-serif` or `serif`. This is truly a shame.

While designers and developers may intend to use specific typefaces for ease of managing various font issues, I would rather websites and applications provide more choices to users. Standards and browsers should also contribute to this effort.

**Comment by mirabilos** [comment]
End users’ local, specific needs should weigh more than the desires of any “web designer”.

**Comment by NightFurySL2001** [comment]
> Apart from some typeface design issues, the system-ui value ties the typeface to the "system" fonts, which takes ability away from users to customize the typeface to their preference using sans-serif or serif. This is truly a shame.

That is a fault on operating system and browser vendors, it has no relation to how system-ui should behave.

> While designers and developers may intend to use specific typefaces for ease of managing various font issues, I would rather websites and applications provide more choices to users. Standards and browsers should also contribute to this effort.

In that case, designers and developers should use sans-serif and serif without system-ui. Still not an issue with W3C definition.

===

This discussion has derailed from a technical discussion of W3C spec to user preferences. IMO, even though system-ui behaviour is bad on Windows, we still require system-ui as a font family option *when* developers and designers want to mimic the original feel of the user's operating system (with or without user preference), and that is definitely a valid use case to discard the notion of deprecating or removing system-ui. If user want to change how system-ui behave, then it should be the task of operating systems and browser vendors on how to do so.

This is not an issue that should be discussed in here at all.

**Comment by Crissov** [comment]
Quite obviously, *any* font that has ”UI“ in its name is intended and designed to be used for short labels etc. within the user interface and not for longer, multi-line texts. This applies equally to any such CSS keyword, `system-ui` in particular. Some typefaces, like Segoe, include separate fonts for use in UIs vs.  prose. If some CSS (framework) authors ignore this, the fault is theirs alone, i.e. it’s not the job of CSS specifications (nor browser / OS / font vendors) to fix it for them.

**Comment by robinmetral** [comment]
Let's recenter on [the spec](https://drafts.csswg.org/css-fonts-4/#system-ui-def). I think that everyone who's been through this thread and researched the topic will agree that:

1. `system-ui` works as intended
2. "as intended" causes issues for end users (e.g. bad rendering of latin text on CJK Windows)

Therefore:

- the implementation of `system-ui` doesn't have to change (it works as intended)
- for the sake of users, the potential pitfalls of using `system-ui` should be made clear in the spec (until OS/browser vendors make sure that i18n issues disappear)

How about adding a warning along the lines of "using `system-ui` can lead to display issues for some user-agents", with a reference to this issue?

**Comment by tats-u** [comment]
> That is a fault on operating system and browser vendors, it has no relation to how system-ui should behave.

NOPE. Windows users may run extremely old apps like an antique. It may expect MS UI Gothic or Meiryo UI, which are former Japanese UI fonts. Windows platform has too many old or even rotten (proprietary) applications to let users choose the system font.

> Still not an issue with W3C definition.

There are too many premises to utilize the current `system-ui` effective:

1. The language of text should match to that of `lang` attribute. (causes unified han shape mismatch issue)
2. If the OS vendor do not want to cause the problem 1., it has to produce a huge CJK unified font like Source Han Sans/Serif or Noto Sans/Serif CJK. It places a significant burden on OS vendors.
3. The text should not be too long. Short label text or its description is ideal.
4. It does not assure that the allocated font is the most beautiful or readable even in, or mostly optimized for long text in the system (except for OSes made by Apple).

Those who abuse `system-ui` will not know them and we should warn them in the specs (or MDN).

>  developers and designers want to mimic the original feel of the user's operating system (with or without user preference), and that is definitely a valid use case to discard the notion of deprecating or removing system-ui.

Agree. I wish designers of frameworks understood it.

> any font that has ”UI“ in its name is intended and designed to be used for short labels etc. within the user interface and not for longer, multi-line text

Segoe UI may be the _only_ exception but I wonder why it is so fervently worshipped because it looks relatively condensed compared to Arial, Open Sans, and Roboto. ~~I wonder if someone have compared it with Arial Nova](https://learn.microsoft.com/typography/font-list/arial-nova) or [Neue Haas Grotesk Text Pro](https://learn.microsoft.com/typography/font-list/neue-haas-grotesk-text-pro) (unfortunately neither are built in Windows for CJK languages by default).~~ Update: they are rather for headings. Calibri or Aptos (Aptos isn't available in Japanese Windows) may be suitable for long text in Windows default fonts? I haven't seen font family definitions that adopt Arial Nova or Neue Haas Grotesk as OS Latin fonts.

> using system-ui can lead to display issues for some user-agents

We should mention "especially long text like documents or blogs". system-ui is sufficient in short UI labels to some extent.
Also, We may have to mention the words "Electron" or "WebView" to raise expected use cases, too.

**Comment by NightFurySL2001** [comment]
> NOPE. Windows users may run extremely old apps like an antique. It may expect MS UI Gothic or Meiryo UI, which are former Japanese UI fonts. Windows platform has too many old or even rotten (proprietary) applications to let users choose the system font.

Older version of Windows like Windows XP allowed users to customise the UI typeface, and that is what should be used if CSS `system-ui` was available at that time. This is definitely the fault on Microsoft on removing customisation options for end users, but I digress.

---

Suggestion text for W3C:

> [!NOTE]
> `system-ui` is dependent on operating system implementation, which may reference user locale and language settings, and provides varying level of text shaping support; this may cause the displayed typeface to be undesirable for some end users *(e.g. Simplified Chinese users might get a monospaced serif font on older version of Windows)*. Note that some operating system vendors does not offer means to customise `system-ui`, unlike browser UAs that generally allow users to customise `sans-serif` or `serif` font family. As the name implies, `system-ui` should be used on UI elements in web application, and not for large paragraphs of text or articles.

**Comment by mirabilos** [comment]
> Older version of Windows like Windows XP allowed users to customise the UI typeface

Some OSes never had such a thing, as it makes no sense for them.

In the case of Firefox on Unix, I can set a lot of things in `chrome/userContent.css` but not a typeface substitution.

Please remove `system-ui` from the spec, it has no place on the web.

**Comment by emilio** [comment]
> In the case of Firefox on Unix, I can set a lot of things in chrome/userContent.css but not a typeface substitution

Slightly off topic but most common Unix DEs allow you to change UI fonts. Also, Firefox on unix (and windows) uses the same font as the menu system font for system-ui, which means that you can set `ui.font.menu` to change it to something else (along with ui.font.menu.{size,weight,italic} to change them as well).

**Comment by tats-u** [comment]
> Older version of Windows like Windows XP allowed users to customise the UI typeface, and that is what should be used if CSS system-ui was available at that time. This is definitely the fault on Microsoft on removing customisation options for end users, but I digress.

I see. However, this fact still does not resolve the problem that a Chinese/Japanese font is assigned to Japanese/Chinese text in a Chinese/Japanese OS expect for pan-CJK fonts like Noto Sans CJK or Source Han Sans. I doubt that the current specifications have an UA assign Microsoft YaHei UI or PinFang SC to a Chinese text where lang=zh even in a Japanese OS.

**Comment by robinmetral** [comment]
@mirabilos a feature with known pitfalls doesn't warrant its removal from the spec. Even if it did, a breaking change would go against the [first design principle](https://www.w3.org/TR/2007/WD-html-design-principles-20071126/#support-existing-content) of the web: support existing content, a.k.a. don't break things.

Quoting from the design principle:

> the fact that something is part of the supported language does not by itself mean that relying on it is condoned or encouraged

I think this is the situation we're in. How about giving feedback on @NightFurySL2001's suggestion in https://github.com/w3c/csswg-drafts/issues/3658#issuecomment-3303510348 for the phrasing of a warning about `system-ui` use? (actually, maybe it's time to open a PR?)

Once we have something we're satisfied with in the spec, I'm happy to open a PR on [mdn/content](https://github.com/mdn/content) to reflect it over there and make the problems more visible to authors (not everyone reads specs).

**Comment by NightFurySL2001** [comment]
> I see. However, this fact still does not resolve the problem that a Chinese/Japanese font is assigned to Japanese/Chinese text in a Chinese/Japanese OS expect for pan-CJK fonts like Noto Sans CJK or Source Han Sans. I doubt that the current specifications have an UA assign Microsoft YaHei UI or PinFang SC to a Chinese text where lang=zh even in a Japanese OS.

@tats-u 

Demo site: https://onecompiler.com/html/43x3qu8n5
A quick check with my friend found that MacOS and iOS do support language-specific tagging in `system-ui`, albeit only tested in English OS. This is a true OS-level text shaping support as SC, TC and JP uses different fonts (PingFang SC, PingFang TC [different 示] and Hiragino Kaku), so I suspect it'll work on Chinese/Japanese OS too. Screenshot of Safari on Mac, Chrome on Mac and Safari on iPad:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/6ebc58ce-dc1b-45e1-8c6f-0de9c27e5453" />
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/cd3dbdd0-9c65-483c-b4d1-25c52f7ca661" />
<img width="1011" height="703" alt="Image" src="https://github.com/user-attachments/assets/ce4266bb-f4c6-4c1d-9687-12236f111edb" />

Android "support" it too like you mentioned, but it's using one singular Noto Sans CJK for pan-CJK support and not on system-level, and thus do break down if I use another font. Shown is my POCO phone that uses MiSans by default on first row _(no pan-CJK support, but P/S: demonstrate that `system-ui` does correctly use what my system is using)_, Noto CJK on second and third row.

<img width="1521" height="703" alt="Image" src="https://github.com/user-attachments/assets/0c4d94f5-d1e7-49d7-a3ec-5fa9dac55f25" />

TL;DR: `system-ui` implementation is highly dependent on OS and UA. If we combine the pros from multiple OS/UA, then `system-ui` would have been a great choice, but we're not in that perfect world.

**Comment by tats-u** [comment]
> A quick check with my friend found that MacOS and iOS do support language-specific tagging in system-ui, albeit only tested in English OS. This is a true OS-level text shaping support as SC, TC and JP uses different fonts (PingFang SC, PingFang TC [different 示] and Hiragino Kaku), so I suspect it'll work on Chinese/Japanese OS too. Screenshot of Safari on Mac, Chrome on Mac and Safari on iPad:

Thank you for your quick investigation. I am glad to hear that. Indeed, UAs in Apple OSes can recognize `lang` attributes even in `system-ui` and make it behave like a virtual Pan-CJK font. I was able to confirm this behavior in my antique iPhone.

https://codepen.io/tats-u/pen/JoGPgxN

![image](https://github.com/user-attachments/assets/c2d64b91-5745-4226-944e-cafabfc21c6b)

c.f. Windows for Japanese + Firefox (1st) / Chrome (2nd):

<img width="691" height="672" alt="Image" src="https://github.com/user-attachments/assets/c0d00a87-7ba9-42b6-bd22-23f435a9e7dc" />

<img width="659" height="709" alt="Image" src="https://github.com/user-attachments/assets/d6178c05-3d02-4065-a470-c2378dcae1d1" />

Pixel + Firefox:

![Screenshot_20250918-224726.png](https://github.com/user-attachments/assets/5e55bb9e-290d-4a2a-9919-42858c3fd2d3)


> thus do break down if I use another font. Shown is my POCO phone that uses MiSans by default on first row (no pan-CJK support, but P/S: demonstrate that system-ui does correctly use what my system is using),

What I had feared happened there. Non-Noto fonts cannot expect the han shape correctness out of locales to which those fonts correspond.

- Windows: 100% fail
- macOS/iOS: 100% pass (thanks to virtual Pan-CJK font by combining some CJK fonts)
- Linux/Android: depends on whether it adopts Noto CJK as UI font (I want to believe that most of major ones do but some definitely do not)

**Comment by tats-u** [comment]
Mandatory:

- Discourage the abuse of system UI in the specifications or MDN

Should we do?

- Force PC/AT OSes (Win/Linux/Android) to emulate Apple OSes' behavior (virtual Pan-CJK fonts if `lang` is CJK) in the specifications—It is relatively easy in Windows because the font name of UI fonts are limited, but is it possible in Linux/Android?
- Add a test case like the above (`lang` attribute sensitiveness) to WPT

---

> no place on the web.

Does have place on Electron or WebView apps.

-----

> system-ui is dependent on operating system implementation, which may reference user locale and language settings, and provides varying level of text shaping support; this may cause the displayed typeface to be undesirable for some end users (e.g. Simplified Chinese users might get a monospaced serif font on older version of Windows). Note that some operating system vendors does not offer means to customise system-ui, unlike browser UAs that generally allow users to customise sans-serif or serif font family. As the name implies, system-ui should be used on UI elements in web application, and not for large paragraphs of text or articles.

> As the name implies, system-ui should be used on UI elements in web application, and should not…

↓

1. As the name implies, system-ui is _intended for use with_ UI elements in web applications, and should not be used…
2. As the name implies, system-ui should be _mainly_ used on UI elements in web applications, and should not be used…

> customise

↓

customize (Sorry for nit)


> text or articles.

↓

text or articles (e.g. on some devices running non-Apple operating systems, the glyph shape does not match what the language specified by the lang attribute expects unlike `sans-serif`).

**Comment by NightFurySL2001** [comment]
> Add a test case like the above (lang attribute sensitiveness) to WPT

Won't work until operating systems fix the issue, as WPT is more focused on browsers/UAs more than operating systems. However it might be a good idea to let the UA vendors to raise bugs/issues towards OS vendors internally..... 🤔

> text or articles (e.g. on some devices running non-Apple operating systems, the glyph shape does not match what the language specified by the lang attribute expects unlike sans-serif).

redundant to "dependent on operating system implementation, which may reference user locale and language settings, and provides varying level of text shaping support". added another example.

Fix:

> [!NOTE]
> `system-ui` is dependent on operating system implementation, which may reference user locale and language settings, and provides varying level of text shaping support; this may cause the displayed typeface to be undesirable for some end users *(e.g. Simplified Chinese users might get a monospaced serif font on older version of Windows; `lang` attribute might not affect displayed typeface in cases like `lang='uk'` in Russian locale or `lang='ja'` in Chinese locale)*. Note that some operating system vendors does not offer means to customize `system-ui`, unlike browser UAs that generally allow users to customise `sans-serif` or `serif` font family. 
> As the name implies, `system-ui` is intended for use with UI elements in web application, and not for large paragraphs of text or articles. This may be useful for hybrid, web or cross-platform applications.

**Comment by robinmetral** [comment]
@NightFurySL2001 PR to make it easier to give feedback/suggest changes? Let's keep this thread for discussing the course of action, not phrasing/spelling (I think the spec uses en-gb 😛)

**Comment by NightFurySL2001** [comment]
Reviewing the spec, there is now also `ui-sans-serif`, `ui-serif`, `ui-monospace`, and `ui-rounded`, which all are similar to the current `system-ui` is intended for. Would these need a warning too?

**Comment by mirabilos** [comment]
Emilio Cobos Álvarez dixit:

>emilio left a comment (w3c/csswg-drafts#3658)
>
>> In the case of Firefox on Unix, I can set a lot of things in
>> chrome/userContent.css but not a typeface substitution
>
>Slightly off topic but most common Unix DEs allow you to change UI
>fonts.

Not running a DE though, plain X11 with evilwm or IceWM.

>Also, Firefox on unix (and windows) uses the same font as the
>menu system font for system-ui, which means that you can set
>`ui.font.menu` to change it to something else (along with

Huh, where? There’s no ui.font in about:config…

**Comment by tats-u** [comment]
> Reviewing the spec, there is now also ui-sans-serif, ui-serif, ui-monospace, and ui-rounded, which all are similar to the current system-ui is intended for. Would these need a warning too?

They are implemented only in Apple's OSes _as of now_, but I think that simpler ones are preferred (e.g. including "see system-ui for details"). I have seen ui-monospace in a main text font once. I wonder what they look like in Windows.

**Comment by NightFurySL2001** [comment]
Actually, it looks like `ui-*` font could be intended for long text/article use? On MacOS `ui-monospace` is highly probable what the terminal is using, which is kind of a long text situation. The main issue would be text shaping support, but that's a minor detail that could be fixed by OS vendor.

**Comment by mirabilos** [comment]
On Fri, 19 Sep 2025, NFSL2001 wrote:

>Actually, it looks like `ui-*` font is intended for long text/article
>use?

No, we have the generic 'serif' and 'monospace' for long text/article
and 'sans-serif' for headlines.

**Comment by tats-u** [comment]
> Actually, it looks like `ui-*` font could be intended for long text/article use? On MacOS ui-monospace is highly probable what the terminal is using, which is kind of a long text situation. 

I don't think Windows has such a font especially for CJK locales. Cascadia Mono (default in Windows Terminal) in the Japanese locale is linked to Yu Gothic UI, which is never be monospace:

<img width="566" height="149" alt="Image" src="https://github.com/user-attachments/assets/97cb713b-84d7-4299-8b7e-fd3ade52883c" />

Windows lacks medium weight (500 in CSS) Japanese fonts (Yu Gothic Medium is not Medium weight but 400-450 in CSS).

**Comment by tats-u** [comment]
[BIZ UD Gothic](https://github.com/googlefonts/morisawa-biz-ud-gothic?tab=readme-ov-file), the default Japanese `monospace` in Windows, provides very readable Japanese glyphs but its Latin glyphs are very quirky and not suitable for programming.

<img width="1058" height="816" alt="Image" src="https://github.com/user-attachments/assets/e63a978e-7a7b-4ebf-b243-9ab4f035a555" />

<img width="443" height="119" alt="Image" src="https://github.com/user-attachments/assets/3a1e5972-554a-40c2-a552-5d2f1bf668f1" />

The below is [a popular programming font made of BIZ UD Gothic and JetBrains Mono](https://github.com/yuru7/udev-gothic):

<img width="428" height="94" alt="Image" src="https://github.com/user-attachments/assets/bb837eae-f3bd-4454-ae83-19687f91cb93" />

**Comment by tats-u** [comment]
The widths of hiragana, katakana, and han glyphs in high-quality Japanese fonts supporting the OpenType feature palt e.g. Noto Sans CJK and Yu Gothic except for Yu Gothic UI are the same by default.
If the font provides a variant font whose name just removed P (e.g. MS PGothic and BIZ UDPGothic), those in it do not share the same width.
I think that han glyphs in Chinese fonts also share the same width but have not investigated it yet.

**Comment by tats-u** [comment]
I just heard about another bug in Yu Gothic UI:

<img width="1538" height="887" alt="Image" src="https://github.com/user-attachments/assets/68c01ae7-9b60-44b7-9599-39d6879fbbb9" />

The Greek letter Ω turns into a different character (small Cyrillic letter и) only when it's bold (Semibold or Bold weights).

https://codepen.io/tats-u/pen/GgjombB
https://zenn.dev/arad/articles/omega-to-cyrillic (Japanese)
https://note.com/minn_1092/n/n2de6227e8224 (Japanese)

**Comment by tats-u** [comment]
The above occurs in not only Japanese but also English or Greek context:

<img width="718" height="496" alt="Image" src="https://github.com/user-attachments/assets/57c283c5-2f7d-4dac-9fca-85cbeef0f069" />

All и in this screenshot are intended to be Ω.

**Comment by jfkthame** [comment]
That looks like it's simply a platform font bug, not really anything to do with CSS. Have you reported it to Microsoft? Nobody else is in a position to fix it.

**Comment by tats-u** [comment]
> Have you reported it to Microsoft?

https://aka.ms/AA11xr5m (Japanese)

> That looks like it's simply a platform font bug, not really anything to do with CSS.

This is merely a casual, freely quotable warning aimed at non-Japanese speakers (especially Latin script users) who are system-ui fanboys trying to cram system-ui into a site or framework’s font stack: “Don’t abuse system-ui indiscriminately, because depending on the environment it can resolve to some buggy, messed-up font.”  The Feedback Hub can’t be viewed by non-Windows purchasers, and the format of links to it doesn’t look permanent, so it’s important to leave evidence in a public place.

I do agree, however, that the CSS spec doesn’t allow any further approach to this problem.

**Comment by tats-u** [comment]
If I could wish for anything, it would be for the browser vendors to update their sans-serif font stacks of Greek-like scripts, so websites wouldn't need to list Latin UI fonts for major operating systems (e.g. Segoe UI, Roboto).

**Comment by NightFurySL2001** [comment]
@tats-u  The W3C CSS specification isn't a place to enforce personal preferences. Telling everyone to drop `system-ui` because it has issues in a specific evironment is a subjective choice, not something that should be imposed on everyone. 

> This is merely a casual, freely quotable warning aimed at non-Japanese speakers (especially Latin script users) who are system-ui fanboys trying to cram system-ui into a site or framework’s font stack

The issue with poor `system-ui` font is very obviously the fault on Windows when `system-ui` is better than developers speifying custom fallback font list on other major operating systems i.e. Android (Roboto/Noto family), Apple and Linux. The i18n implementation of `system-ui` on Apple device is even better than using `sans-serif`, which is a plus of using `system-ui` if they want to mimic the operating system feel.

Given that Windows render long texts in Segoe UI eg EULA on installation, Windows do expect the system font i.e. `system-ui` to be usable for long text too. The issue is just that Windows developers have bad taste, worse implementations and nightmare customer support. (all major `system-ui` failure reported so far only appears on Windows with CJK language)

As a person in [other comment thread](https://github.com/JLHwung/postcss-font-family-system-ui/issues/210#issuecomment-531508900) says, and I quote:

> must we avoid an spec because an OS fails at Chinese [editor: and Japanese] text?

---

If you really care that Japanese Windows shouldn't use Yu Gothic UI, you should submit this feedback to Microsoft to consider using another font. The benefits of using `system-ui` for cross-compatibility isn't really outweighted by the poor implementation on Windows. If you *realllly* doesn't want `system-ui`, maybe instead of suggesting others to remove it, add a JavaScript that detects Windows and override the CSS family. Note that i18n on Apple works better on `system-ui` than `sans-serif`.

**Comment by tats-u** [comment]
> Given that Windows render long texts in Segoe UI eg EULA on installation

Mi¢ro$oft has no incentive to render the EULA in a readable font. By deliberately rendering it in a hard-to-read font, they increase the probability that users will miss clauses favorable to Mi¢ro$oft.

> If you really care that Japanese Windows shouldn't use Yu Gothic UI, you should submit this feedback to Microsoft to consider using another font.

https://aka.ms/AA4rj5q

https://x.com/search?q=%22Yu%20Gothic%20UI%22

It seems you don't understand even the slightest bit of frustration among Japanese Windows users. This issue of the Japanese Windows system font glyphs being terrible has been pointed out by many Japanese users who notice the differences between fonts for many years, yet Microsoft has stubbornly ignored it. While Yu Gothic UI has gained some positive recognition in PowerPoint slides, its overall design reputation remains negative.

<img width="1165" height="597" alt="Image" src="https://github.com/user-attachments/assets/41c143f8-0efe-4d26-a6bd-2e2eeedba929" />

↑ This image shows why Windows adopts overly narrow fonts that inherit the width of MS UI Gothic, such as Yu Gothic UI, as the default Japanese UI font. The Japanese UI font were developed as a compromise to avoid using half-width katakana, which is more difficult to read.


> JavaScript that detects Windows and override the CSS family

Layout shifts occur when JavaScript loads. This is completely unacceptable. The method to detect the User-Agent or Accept-Language on the server cannot be applied to static .html files.

> Note that i18n on Apple works better on system-ui than sans-serif.

In this case, -apple-system + BlinkMacSystemFont would be sufficient.

> isn't really outweighted by the poor implementation on Windows.

Call me again when the market share of macOS (and Linux) in the (desktop/laptop) computer market significantly surpasses Windows.

**Comment by tats-u** [comment]
There are still many legacy desktop applications in Japan that rely on the narrow character width of MS UI Gothic. If these applications are forced to use standard-width fonts like Yu Gothic or Noto Sans JP instead of Yu Gothic UI or Meiryo UI, which have nearly identical character widths, it will likely lead to a series of tragedies where text overflows, as shown in the image above where text is truncated with ellipses.

The system-ui implementation on macOS isn't perfect either, with Safari displaying Japanese glyphs slightly smaller compared to other browsers, resulting in different rendering.

**Comment by Sora2455** [comment]
If there exist applications that break when they're not viewed with a particular font, then:

1. That seems like very bad design
2. They should specify that font in their application's design, and not leave it up to the OS?

Neither of which are in scope for this WG, let alone this issue?

**Comment by tats-u** [comment]
> They should specify that font in their application's design, and not leave it up to the OS?

This is why MS UI Gothic becomes the default in Windows Forms.
WPF uses the default system font in the current locale (Yu Gothic UI for Japanese Windows 11) by default unless specified.

If Microsoft were to change system fonts to Noto Sans JP, Japanese WPF applications that don't specify a font would experience design breaks.

system-ui's behavior is considered to be equivalent to that of WPF. For quick-and-dirty solutions to use it only with domestic users of web applications or websites (outside e.g. Japan), it's perfectly adequate (unless a foreigner visits your page or app).

**Comment by tats-u** [comment]
The YaHei and JhengHei fonts in Simplified and Traditional Chinese show slight differences between their UI and non-UI variants, but do Chinese designers find these differences noticeable?

- The UI variant has slightly tighter line spacing
- The UI variant uses proportional Western-style quotation marks instead of full-width ones

<img width="242" height="349" alt="Image" src="https://github.com/user-attachments/assets/730b0bc9-2ca0-4cc7-9401-4570192c049f" />

PS: These quotation marks will be overwritten by Segoe UI, though.
