### ISSUE TITLE
Hebrew in Firefox reversed characters [ruby]

### ISSUE THREAD

**Issue by itkind** [w3c/csswg-drafts#4409]
Hi, I tried many things but firefox doesn't want to display the Hebrew in the right direction. This is like it looks: 
![image](https://user-images.githubusercontent.com/22380863/66596137-a0665f80-eb9c-11e9-91c1-180d00f4b2f5.png)

This is how it should look: 
![image](https://user-images.githubusercontent.com/22380863/66596384-12d73f80-eb9d-11e9-9926-532081264720.png)

It works only: 1. if the characters are reversed than firefox puts them right, 2. when not using ruby firefox recognizes the right direction, 3. when using an other browser but than the rt and rtc doesnt work.

I tried bidi-override, but nothing works.

**Comment by tabatkins** [comment]
`<ruby dir=rtl>` will give you the base ordering you want.

[The Ruby spec](https://drafts.csswg.org/css-ruby/#bidi) defines that ruby bases are *not* implicitly re-ordered based on the text inside; instead they pay attention to the explicit direction of the ruby container.

**Comment by itkind** [comment]
> 
> 
> `<ruby dir=rtl>` will give you the base ordering you want.
> 
> [The Ruby spec](https://drafts.csswg.org/css-ruby/#bidi) defines that ruby bases are _not_ implicitly re-ordered based on the text inside; instead they pay attention to the explicit direction of the ruby container.

This doesn't work, try it: <ruby dir=rtl>
  <rb>בָּגַֽדְנוּ</rb>
  <rt>wir waren untreu</rt>
</ruby>

**Comment by AmeliaBR** [comment]
This looks like a problem specifically with Firefox, rather than with the CSS specification. (Chrome, for example, gives the rendering you expect for the markup with explicit `dir` value.)

You can file bugs on Firefox here: https://bugzilla.mozilla.org You can log in with your GitHub account.

If the Firefox developers determine that the specification isn't clear enough about what to do, they will let us know!  But since we do have Firefox developers in the CSS working group, please reply here with a link to the bug you create so they know to look into it.

**Comment by itkind** [comment]
I reported the bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1587937

**Comment by tabatkins** [comment]
> This doesn't work, try it: `<ruby dir=rtl> <rb>בָּגַֽדְנוּ</rb> <rt>wir waren untreu</rt> </ruby>`

Ooh, indeed, Firefox isn't doing bidi reordering *at all* within ruby bases. That's absolutely a Firefox bug. Thanks for reporting it!

**Comment by itkind** [comment]
Looks like Firefox is not interested in fixing this bug. Some one wrote: 

> Looks like I know this bug and thought no one would ever do this so made it low priority.
If anyone is really trying to do that, I think we should fix it.

that's too bad.

**Comment by upsuper** [comment]
> Looks like Firefox is not interested in fixing this bug. Some one wrote:

That's me. I'm very interested in fixing this bug, and that's why I ni?ed myself there. It would be the next bug to investigate when I have time.

**Comment by itkind** [comment]
> Looks like Firefox is not interested in fixing this bug. Some one wrote:
> 
> That's me. I'm very interested in fixing this bug, and that's why I ni?ed myself there. It would be the next bug to investigate when I have time.

Oh sorry, than I misunderstood you. Great news! Thanks

**Comment by hftf** [comment]
Update: should now be fixed. https://bugzilla.mozilla.org/show_bug.cgi?id=1144465

**Comment by itkind** [comment]
This still doesn't work, try it 
`<ruby dir=rtl> <rb>בָּגַֽדְנוּ</rb> <rt>wir waren untreu</rt> </ruby>`
