### ISSUE TITLE
[css-inline] vertically align to middle of cap height

### ISSUE THREAD

**Issue by tylersticka** [w3c/csswg-drafts#4707]
`vertical-align: middle` will align an element with the baseline of text minus half its x-height. This makes it a poor fit for glyph-sized elements like icons, which will always look a tad too low. Ideally we’d have a keyword (`vertical-align: text-middle`?) that would align with the middle of the cap height of the typeface instead…

![The text "Favorite" with an adjacent heart icon and guidelines for type anatomy. The top version is middle-aligned with the text's x-height, while the bottom version is middle-aligned with the text's cap-height](https://user-images.githubusercontent.com/69633/73290290-09f19480-41b3-11ea-8248-cd448de4eaea.png)

In lieu of this property, I see two dominant techniques for accomplishing this:

- The icon position is adjusted manually, using `top: -1px` or similar. This requires the icon to be `inline-block`, since other positioning techniques will conflict with the `top` value.
- The icon and text must be wrapped in a container with `display: flex; align-items: center` or similar. But this prevents the icon from being used inline.

(I was [encouraged to submit this issue](https://twitter.com/fantasai/status/1220851780357148674) after [writing about the idea](https://cloudfour.com/thinks/some-imaginary-css/#align-to-typeface-median).)

**Comment by fantasai** [comment]
Yeah, `middle` should have been called `x-middle`! We could call the new variant `cap-middle`.

I'll note that we also have `central` now, which is geared towards ideographic content, and `mathematical` which runs through the middle of the equals sign; it might be interesting to see how closely those track the cap-middle.

**Comment by fantasai** [comment]
(My current thoughts on this, fwiw, is to defer on adding cap-middle until we sort out https://github.com/w3c/csswg-drafts/issues/5244 and see if `central` mostly solves the problem in the meantime.)

**Comment by chearon** [comment]
There is a robust way to do this now, with CSS2's `vertical-align: <length>`, if you know (1) the height of the box and (2) the font's cap-height in EM units [1]:

```css
--font-cap-height: 0.71em; /* roboto */
--box-size: 16px;
vertical-align: calc((var(--font-cap-height)/2 - var(--box-size)/2));
```

By using `vertical-align` instead of `bottom`/`translate`, there won't be any line overlap in case the font is smaller than the box

[1] Drag the font to the [opentype.js inspector](https://opentype.js.org/font-inspector.html) divide `OS/2->sxHeight` by `head->unitsPerEm` and that's your `--font-cap-height` in `em` units

**Comment by Bosch-Eli-Black** [comment]
Yes, please! 🙂  I run into this all the time.

Also, is there a proposal to add `vertical-align: cap`? If one has an icon with `vertical-align: start`, the icon appears to be slightly above its accompanying text, since it's aligned to start at the cap height + ascender height. It seems like ideally there'd be a way to align icons so that they start at the top of the cap (the bottom of the ascender).

**Comment by kizu** [comment]
I just published a post in my blog about how we can work around the absence of this feature using the newly available `cap` unit: https://blog.kizu.dev/cap-height-align/

However, both methods I outlined in my post are not ideal: having a readily available value for `vertical-align` to align stuff to the middle of the font's cap-height will be better than hacky calculations in every regard.

It would be nice to see either some progress on this, or on https://github.com/w3c/csswg-drafts/issues/5244 (or any browser interest in `central` value, which was not implemented by anyone, as it seems).

**Comment by vrubleg** [comment]
Maybe it's time to reconsider this again?

**Comment by vrubleg** [comment]
Now we have `text-box-trim`, which is somewhat related and helps with this use case, but it still doesn't fully resolve this issue.
