### ISSUE TITLE
[css-contain-3] Move style queries of standard properties to level 4

### ISSUE THREAD

**Issue by anttijk** [w3c/csswg-drafts#7185]
Style queries for standard (non-custom) properties are currently severely underspecified and have many open questions in terms of behavior, implementability and usefulness.

Some examples:

How does `style(width: calc(…))` behave? 

Will authors understand why this (or any particular value syntax) is available with `style()` but not with the usual size query syntax `()` especially when feature and property names are the same? 

As far as I know there is no definition of “equality” in general between the computed style and some arbitrary author property value. Engines have some internal notion of equality between two computed styles but that doesn’t seem sufficient here. This would need to be fully specified in all cases.

How about shortcut properties?

What happens with `style(color:inherit)` or say `style(color:revert-layer)`? Are we supposed to run full style resolution pipeline in middle of selector matching to determine the value being queried? Based on https://github.com/w3c/csswg-drafts/issues/7080 it sounds like there are plans to limit some but not all global values. How do authors know what is allowed? 

Possible spec/implementation shortcuts for above (“just serialize and use string equality”) have major performance concerns.

Is this feature useful as specified? Exact equality is very limiting. Many interesting properties are numbers or multidimensional objects like colors. Size queries support ranges for a reason.

How does this interact with animations? Accelerated ones where style is not resolved for every frame?

There is a huge testing matrix for this with 600+ properties (and infinite amount of complex values). 

It seems to me that this feature as specified adds a massive amount of complexity for very limited utility. A serious implementation effort would surely find way more questions. 

Container queries without style queries (or style queries limited to custom properties/variables) offers a nice set of functionality. It seems unwise to delay those features in pursuit of this.

**Comment by mirisuzanne** [comment]
If it makes sense for implementors to draw a line between custom & standard properties, and one is significantly easier than the other, I agree that custom properties are a useful first step on their own -- even if standard properties get marked as at-risk. I agree that I wouldn't want this to dramatically delay the release of size queries.

**Comment by mirisuzanne** [comment]
The proposal here is to defer style queries of standard properties to level 4, and consider if querying the computed value is actually what we want here. I think that makes sense, and we may be able to resolve on it async.

**Comment by astearns** [comment]
The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

**Proposed Resolution**: Defer style queries of standard properties to level 4 (to allow faster progress for style queries for custom properties

**Comment by astearns** [comment]
**RESOLVED**: Defer style queries of standard properties to level 4 (to allow faster progress for style queries for custom properties

**Comment by jlukic** [comment]
Came here after reviewing the related MDN / Google materials on CSS Style Queries. It doesn't seem like any of the documentation mention that it does not resolve calculated values. 

Amusingly you can match the exact calc value as a string

```css
.container {
  container: test / inline-size;
  --test: calc(1px + 1px);
}
@container test style(--test: 2px) {
  /* in your dreams */
  div {
    border: 3px solid red;
  }
}
@container test style(--test: calc(1px + 1px)) {
  /* this works! */
  div {
    border: 3px solid purple;
  }
}
```

https://jsfiddle.net/20as4jgk/

**Comment by lilles** [comment]
> Came here after reviewing the related MDN / Google materials on CSS Style Queries. It doesn't seem like any of the documentation mention that it does not resolve calculated values.
> 
> Amusingly you can match the exact calc value as a string
> 
> ```css
> .container {
>   container: test / inline-size;
>   --test: calc(1px + 1px);
> }
> @container test style(--test: 2px) {
>   /* in your dreams */
>   div {
>     border: 3px solid red;
>   }
> }
> @container test style(--test: calc(1px + 1px)) {
>   /* this works! */
>   div {
>     border: 3px solid purple;
>   }
> }
> ```
> 
> https://jsfiddle.net/20as4jgk/

The thing is that `--test` is not a registered custom property, so it is merely a string and calc() does not have a meaning in that context other than its string representation.

If you register the custom property as a length, you can both query calc() and the absolute value:
```html
<!DOCTYPE html>
<style>
  @property --test {
    syntax: "<length>";
    inherits: false;
    initial-value: 0px;
  }

  #container1 {
    --test: calc(50px + 50px);
  }
  #container2 {
    --test: 100px;
  }
  @container style(--test: 100px) {
    #target1 {
      color: green;
    }
  }
  @container style(--test: calc(40px + 60px)) {
    #target2 {
      color: green;
    }
  }
</style>
<div id="container1">
  <div id="target1">Green</div>
</div>
<div id="container2">
  <div id="target2">Green</div>
</div>
```

**Comment by jlukic** [comment]
Thanks for your quick reply, that makes sense what you're saying and appreciate your help here.  

I am still however unable to get `@property` definitions working with a container name. Perhaps what I am witnessing is an issue in chrome with the combination of the two, or am i missing something?

I've extended your example to show you what I'm talking about: 

https://jsfiddle.net/qeLyczpj/

```html
<div id="container1">
  <div id="target1">Green</div>
</div>
<div id="container2">
  <div id="target2">Green</div>
</div>
```
```css
  @property --test {
    syntax: "<length>";
    inherits: true;
    initial-value: 0px;
  }
  html {
    --test: calc(50px + 50px);
  }
  #container1 {
    container: container1 / inline-size;
  }
  #container2 {
    container: container2 / inline-size;
  }
  
  /* global works */
  @container style(--test: 100px) {
    #target1 {
      color: red;
    }
    #target2 {
      color: red;
    }
  }
  
  /* but not with container */
  @container target1 style(--test: 100px) {
    #target1 {
      color: green;
    }
  
  }
  @container target2 style(--test: calc(40px + 60px)) {
    #target2 p {
      color: green;
    }
  }

**Comment by lilles** [comment]
> Thanks for your quick reply, that makes sense what you're saying and appreciate your help here.
> 
> I am still however unable to get `@property` definitions working with a container name and the prop inheriting. Perhaps what I am witnessing is an issue in chrome with the combination of the two, or am i missing something?
> 
> I've extended your example to show you what I'm talking about:
> 
> https://jsfiddle.net/qeLyczpj/

It works for me if I fix the typos you made (container name typos and extra 'p' in selector). This is a spec issue, so we should not really discuss this here. I'll remove these comments after a day or so to not clutter the spec issue.

**Comment by jlukic** [comment]
Sorry that fiddle was typo town USA, apologies for what was entirely my error. 

I think what is causing my confusion is that my real world use case is actually **subtly different and doesnt seem to work** since the value uses a mixture of unit types `%` with `px`.

I'm trying to use style queries for a calc that would "flip" when a dynamic breakpoint is met, this was suppose to be a workaround for `@media` declarations lack of css custom property support.

Something like
```css
:root {
  --card-stackable-breakpoint: 700px; /* user can override this */
  --card-stackable-comparator: max(calc(100% - var(--card-stackable-breakpoint)), 0px);
} 
@container component style(--card-stackable-comparator: 0px) {
  //  stack cards
}
```

You can see when the `%` value is introduced even if it is `0%` it seems to no longer work as in this jsfiddle https://jsfiddle.net/cm102pq5/2/

Let me know if you have any thoughts, or any oversights I seem to be making.

----

This is being used in a new web component framework I'm working on for the rewrite of Semantic UI. You can see examples like this [card search](https://next.semantic-ui.com/examples/card-search) would be a good target showcasing this approach. (The docs are only half written so please ignore)

**Comment by svgeesus** [comment]
Since [contain 3 is now empty](https://drafts.csswg.org/css-contain-3/#style-container) and what used to be there (and was resolved to move to contain 4] is [now in conditional 5](https://drafts.csswg.org/css-conditional-5/#container-queries) it seems that this can be closed? And no further edits are needed?
